### PR TITLE
Add Deployed versions + New Services

### PR DESCRIPTION
**Pull request by larsl-net**
Add deployed_verion to `synapse` and `awx`.
Update the deployed_version for `netbox` from regex to an API call.

The `awx` integration is untested (based on the [docs](https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/System_Configuration/System_Configuration_ping_list)) as I am not running `awx`. 
Can anyone test it with a real instance?

Added [opnsene/core](https://github.com/opnsense/core)

### CODE REVIEW

**Comment by JosephKav** [comment]
That AWX URL would need `?format=json` on the end. And unfortunately that query gives the version of AWX rather than the version of AWX-Operator. Not too big of a deal, would just need a change in the github repo that's looked at (`ansible/awx`)
`https://awx.example.io/api/v2/ping/?format=json`
```json
{
  "ha": false,
  "version": "21.0.0",
  "active_node": "awx-787964bd4c-f82j4",
  "install_uuid": "7404fc2b-d257-4551-9373-53419560d576",
  "instances": [
    {
      "node": "awx-787964bd4c-f82j4",
      "node_type": "control",
      "uuid": "78c113c1-ca59-4744-be17-883bae0d5698",
      "heartbeat": "2022-05-16T18:56:47.020834Z",
      "capacity": 119,
      "version": "21.0.0"
    }
  ],
  "instance_groups": [
    {
      "name": "controlplane",
      "capacity": 119,
      "instances": [
        "awx-787964bd4c-f82j4"
      ]
    },
    {
      "name": "default",
      "capacity": 0,
      "instances": []
    }
  ]
}
```

**Comment by larsl-net** [comment]
@JosephKav Thanks for testing.
I have converted the awx part into a separate service.

**Comment by larsl-net** [comment]
Now all of my services should be added.

I now have 33 services in my config of which 28 use the deployed_version. :smiley:

**Comment by JosephKav** [comment]
> Now all of my services should be added.
> 
> I now have 33 services in my config of which 28 use the deployed_version. 😃

Wow that's a lot! Glad you're still enjoying it and contributing useful stuff to the docs :)

**Pull request merged**
